### ISSUE TITLE
set up back end

### ISSUE THREAD

**Issue by chelseamarfil** [MarcM1250/491A-G2SS#4]

**Comment by chelseamarfil** [comment]
2nd part of the tutorial I followed for Angular set up here: https://medium.com/codingthesmartway-com-blog/angular-6-mean-stack-crash-course-part-2-implementing-the-back-end-642567e16bb9.
Developer can follow this tutorial but make features specific to our app where appropriate.

**Comment by BornIncompetence** [comment]
I have no clue why I was having so many errors before, but now I managed to send HTTP requests with an Express app, now it's a matter of connecting Express to MongoDB
